-- Reactive.nvim:
--    Highlight cursor and cursorline depending on mode.
--
-- gh: https://github.com/rasulomaroff/reactive.nvim
return {}
-- return {
--   {
--     "rasulomaroff/reactive.nvim",
--     event = "ModeChanged",
--     opts = {
--       builtin = {
--         cursorline = true,
--         cursor = true,
--         modemsg = true,
--       },
--     },
--   },
-- }
